version: '3.3'

services:
  postgresql:
    image: 'postgres:latest'
    container_name: 'postgres'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    command: postgres -c 'max_connections=300'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: